/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEffectModalComponent: typeof import('./src/components/AddEffectModalComponent.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    DebugComponent: typeof import('./src/components/DebugComponent.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EffectBadgeComponent: typeof import('./src/components/EffectBadgeComponent.vue')['default']
    EquipmentComponent: typeof import('./src/components/EquipmentComponent.vue')['default']
    EquipmentSlotComponent: typeof import('./src/components/EquipmentSlotComponent.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillComponent: typeof import('./src/components/SkillComponent.vue')['default']
    SkillTabComponent: typeof import('./src/components/SkillTabComponent.vue')['default']
    StepComponent: typeof import('./src/components/StepComponent.vue')['default']
    StepListComponent: typeof import('./src/components/StepListComponent.vue')['default']
    TabComponent: typeof import('./src/components/TabComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
