/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEffectModalComponent: typeof import('./src/components/AddEffectModalComponent.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ControlPanelComponent: typeof import('./src/components/ControlPanelComponent.vue')['default']
    DebugComponent: typeof import('./src/components/DebugComponent.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EffectBadgeComponent: typeof import('./src/components/EffectBadgeComponent.vue')['default']
    EquipmentComponent: typeof import('./src/components/EquipmentComponent.vue')['default']
    EquipmentSlotComponent: typeof import('./src/components/EquipmentSlotComponent.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    ImportExportModalComponent: typeof import('./src/components/ImportExportModalComponent.vue')['default']
    Message: typeof import('primevue/message')['default']
    NotificationComponent: typeof import('./src/components/NotificationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillComponent: typeof import('./src/components/SkillComponent.vue')['default']
    SkillEffectModal: typeof import('./src/components/SkillEffectModal.vue')['default']
    SkillTabComponent: typeof import('./src/components/SkillTabComponent.vue')['default']
    StepComponent: typeof import('./src/components/StepComponent.vue')['default']
    StepListComponent: typeof import('./src/components/StepListComponent.vue')['default']
    StepModalComponent: typeof import('./src/components/StepModalComponent.vue')['default']
    TabComponent: typeof import('./src/components/TabComponent.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
